language: python
python:
    - 2.7
cache: pip

install:
    # portaudio is required for pyaudio
    - sudo apt-get install portaudio19-dev

    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
script:
    - coverage run --source=mediator_bot setup.py test
after_success:
    coveralls
