sudo: required
language: python
python:
    - 2.7
cache: pip

services:
  - docker

env:
  global:
    - toolset_branch: master
    - server_type: travis
    - used_modules: check_cache,check_build,code_style_check,check_deb_make,codecov_tool
    - remote_shell_script: 'https://raw.githubusercontent.com/shadow-robot/sr-build-tools/$toolset_branch/bin/sr-run-ci-build.sh'

script:
  - curl -s "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" | bash -x /dev/stdin "$toolset_branch" $server_type $used_modules

install:
    # portaudio is required for pyaudio
    - sudo apt-get install portaudio19-dev

    - pip install -r requirements.txt
    - pip install coverage
    - pip install coveralls
script:
    - coverage run --source=mediator_bot setup.py test
after_success:
    coveralls
